name: Deploy to GoDaddy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy and Build via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export TERM=xterm
            cd ~/public_html
            git fetch origin
            git reset --hard origin/main
            cd ~/public_html/stc_gld
            npm ci
            npm run build
            printf 'RewriteEngine On\nRewriteBase /stc_gld/\nRewriteCond %%{REQUEST_FILENAME} !-f\nRewriteCond %%{REQUEST_FILENAME} !-d\nRewriteRule ^ build/index.html [QSA,L]\n' > ~/public_html/stc_gld/.htaccess
            printf 'RewriteEngine On\nRewriteBase /stc_gld/build/\nRewriteCond %%{REQUEST_FILENAME} !-f\nRewriteCond %%{REQUEST_FILENAME} !-d\nRewriteRule ^ index.html [QSA,L]\n' > ~/public_html/stc_gld/build/.htaccess
            find ~/public_html/stc_gld/build -type d -exec chmod 755 {} \;
            find ~/public_html/stc_gld/build -type f -exec chmod 644 {} \;
            echo "Deployed at $(date)"